### ISSUE TITLE
Steps of "To create a custom shadow copy schedule" do not seem to work

### ISSUE THREAD

**Issue by MajorCatastrophe** [awsdocs/amazon-fsx-windows-user-guide#12]
**Step one says to enter:**
$trigger1 = new-scheduledTaskTrigger -weekly -DaysOfWeek Monday,Tuesday,Wednesday,Thursday,Friday -at 06:00

**This results in the error:**
At line:1 char:1
+ $trigger1 = new-scheduledTaskTrigger -weekly -DaysOfWeek Monday,Tuesd ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Assignment statements are not allowed in restricted language mode or a Data section.
At line:1 char:1
+ $trigger1 = new-scheduledTaskTrigger -weekly -DaysOfWeek Monday,Tuesd ...
+ ~~~~~~~~~
A variable that cannot be referenced in restricted language mode or a Data section is being
referenced. Variables that can be referenced include the following: $PSCulture, $PSUICulture, $true,
$false, $null.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AssignmentStatementNotSupportedInDataSection

**===== ALSO ========**

set-fsxshadowcopyschedule -scheduledtasktriggers $Using:trigger1,$Using:trigger2 -Confirm:$false }

**results in:**

At line:1 char:98
+ ... heduledtasktriggers $Using:trigger1,$Using:trigger2 -Confirm:$false }
+                                                                         ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by rmarcuce** [comment]
We are working on a resolution to the issue you've raised. Thanks for bringing to our attention.
