### ISSUE TITLE
mal formed object DomainControllers

### ISSUE THREAD

**Issue by witaloandrade** [awsdocs/amazon-fsx-windows-user-guide#19]
mal formed object DomainControllers line 614, from https://docs.aws.amazon.com/fsx/latest/WindowsGuide/samples/AmazonFSxADValidation.zip

$DomainControllers[$DCName] = [PSCustomObject]@{
  Name = $AResult.Name
 IPAddress = $AResult.IPAddress
 Priority = $SrvResult.Priority
 Weight = $SrvResult.Weight
}

The object Name is null, so it is not valid to proceed with the testing.

Here is the error:

a
Test 1 - Validate EC2 Subnets ...
Found region us-west-2 from EC2 instance metadata

SubnetId                 VpcId                 AvailabilityZoneId CidrBlock
--------                 -----                 ------------------ ---------
subnet-12345  vpc-12345 usw2-az2           10.92.30.128/26

Test 2 - Validate connectivity with DNS Servers ...

Found the following XXX Domain Controllers by querying _ldap._tcp.dc._msdcs.local.com:

Name IPAddress Priority Weight
---- --------- -------- ------
                      0    100
                      0    100
                      0    100
                      0    100
                      0    100
                      0    100
                      0    100
                      0    100
                      0    100
                      0    100
                      0    100

**Comment by rmarcuce** [comment]
Devs are working to update the script. Thanks for bringing this to our attention.
