### ISSUE TITLE
table accuracy - amazon-fsx-windows-user-guide/doc_source/performance.md 

### ISSUE THREAD

**Issue by ashwallace** [awsdocs/amazon-fsx-windows-user-guide#9]
section: Impact of Storage Capacity on Performance
there is a small 3x3 table, it shows HDD having the same throughput and IOPS per TiB...surely thats not right? that would also mean a 1 MB IO size, my understanding that is pretty rare also. it would be good to see a correction if applicable, and some IO size discussion.

**Comment by rmarcuce** [comment]
Updating the table in GitHub today. sorry for the delayed response.
